#include <Arduino.h>

#ifndef EEPROM_H
#define EEPROM_H

#define EEPROM_ADDR 0x50

// current length, but really LIGHTS can use all of `0x0-`
#define EEPROM_LIGHTS_MEM_LENGTH 6
#define EEPROM_LIGHTS_MEM_START 0x00
#define EEPROM_LIGHTS_MODE (EEPROM_LIGHTS_MEM_START + 0)
#define EEPROM_LIGHTS_BRIGHTNESS (EEPROM_LIGHTS_MEM_START + 1)
#define EEPROM_LIGHTS_SPEED (EEPROM_LIGHTS_MEM_START + 2)
#define EEPROM_LIGHTS_DIRECTION (EEPROM_LIGHTS_MEM_START + 3)
#define EEPROM_LIGHTS_COLOR (EEPROM_LIGHTS_MEM_START + 4)
#define EEPROM_LIGHTS_THEME_COLOR (EEPROM_LIGHTS_MEM_START + 5)

// current length, but really HRDWR can use all of `0x1-`
#define EEPROM_HRDWR_MEM_LENGTH 2
#define EEPROM_HRDWR_MEM_START 0x10
#define EEPROM_HRDWR_PLUG (EEPROM_HRDWR_MEM_START + 0)
#define EEPROM_HRDWR_TRIGGER (EEPROM_HRDWR_MEM_START + 1)

#endif